service: posts

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    POSTS_TABLE: db-dev-posts

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: posts
          method: get
          cors: true

  create:
    handler: create.create
    events:
      - http:
          path: create-post
          method: post
          cors: true

plugins:
  - serverless-offline
