service: users

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    USERS_TABLE: db-dev-users

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: users
          method: get
          cors: true

  create:
    handler: create.create
    events:
      - http:
          path: create-user
          method: post
          cors: true

plugins:
  - serverless-offline
